// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlr9DWRWbdJBwiy6DppWpCs9-YNdhiok',
    appId: '1:912440276866:web:0c8589af41ed468be3819b',
    messagingSenderId: '912440276866',
    projectId: 'rental-tax-port',
    authDomain: 'rental-tax-port.firebaseapp.com',
    storageBucket: 'rental-tax-port.appspot.com',
    measurementId: 'G-H5DYYS3J0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Qh1NqHrf3SVLHR86JeZ-nWL_sxyGJ9M',
    appId: '1:912440276866:android:589ff0731bcdb9c3e3819b',
    messagingSenderId: '912440276866',
    projectId: 'rental-tax-port',
    storageBucket: 'rental-tax-port.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBl3AZBmPW2paCDO2Rj_cqyjHnfcdXrTQ',
    appId: '1:912440276866:ios:be1044eb2b66cf8de3819b',
    messagingSenderId: '912440276866',
    projectId: 'rental-tax-port',
    storageBucket: 'rental-tax-port.appspot.com',
    iosClientId: '912440276866-3rp075l1amqup5bg2lpr5iccfsc78eas.apps.googleusercontent.com',
    iosBundleId: 'com.rentaltaxport.rentalTaxPort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBl3AZBmPW2paCDO2Rj_cqyjHnfcdXrTQ',
    appId: '1:912440276866:ios:be1044eb2b66cf8de3819b',
    messagingSenderId: '912440276866',
    projectId: 'rental-tax-port',
    storageBucket: 'rental-tax-port.appspot.com',
    iosClientId: '912440276866-3rp075l1amqup5bg2lpr5iccfsc78eas.apps.googleusercontent.com',
    iosBundleId: 'com.rentaltaxport.rentalTaxPort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxlr9DWRWbdJBwiy6DppWpCs9-YNdhiok',
    appId: '1:912440276866:web:afd94c77efe3b91de3819b',
    messagingSenderId: '912440276866',
    projectId: 'rental-tax-port',
    authDomain: 'rental-tax-port.firebaseapp.com',
    storageBucket: 'rental-tax-port.appspot.com',
    measurementId: 'G-23QLJNVFP9',
  );
}
